# CodeRabbit Configuration for ComposeMusicPlayer
# Based on: https://docs.coderabbit.ai/getting-started/configure-coderabbit

# 기본 설정
chat:
  enabled: true

summarize:
  enabled: true

# 리뷰 설정
reviews:
  pull_requests:
    enabled: true
    
# 코드 분석 설정
code_analysis:
  enabled: true
