# CodeRabbit Configuration for ComposeMusicPlayer
# Based on: https://docs.coderabbit.ai/getting-started/configure-coderabbit

# 한국어 설정
language: "ko-KR"

# Early Access 기능 비활성화
early_access: false

# 리뷰 설정
reviews:
  # 리뷰 프로필: chill (너무 빡세지 않게)
  profile: "chill"
  
  # 코드래빗이 리뷰 완료 후 자동으로 PR 승인
  request_changes_workflow: true
  
  # 고수준 요약 활성화  
  high_level_summary: true
  
  # 시(poem) 형태의 요약 활성화
  poem: true
  
  # 리뷰 상태 표시
  review_status: true
  
  # 워크스루 접기 비활성화 (상세히 보기)
  collapse_walkthrough: false
  
  # 자동 리뷰 설정
  auto_review:
    enabled: true
    drafts: false

# 채팅 설정
chat:
  auto_reply: true

# 요약 설정
summarize:
  enabled: true
