name: AOS-ktlint

on:
  pull_request:
    branches:
      - main
      - AOS-develop
  push:
    paths:
      - '**.kt'

jobs:
  editorconfig:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker
  ktlint:
    name: AOS-ktlint
    runs-on: ubuntu-latest
    steps:
      - name: checkout mindsync
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: ktlint
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # 자동 제공
          reporter: github-pr-check
