name: AOS-ktlint

on:
  pull_request:
    branches:
      - main
      - AOS-develop
  push:
    paths:
      - '**.kt'

jobs:
  ktlint:
    name: AOS-ktlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mindsync
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Run ktlint with debug
        run: ./ktlint --debug

      - name: Run ktlint
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
